/Users/cjr/Projects/WeatherTracker/.venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/cjr/Projects/WeatherTracker/dailyWeatherTracker.py", line 24, in <module>
    creds = ServiceAccountCredentials.from_json_keyfile_name(creds_path, scope)
  File "/Users/cjr/Projects/WeatherTracker/.venv/lib/python3.9/site-packages/oauth2client/service_account.py", line 219, in from_json_keyfile_name
    with open(filename, 'r') as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: 'weather-creds.json'
zsh: command not found: 0
/bin/sh: /Users/cjr/Projects/WeatherTracker/.venv/bin/python: No such file or directory
